// 1.hello-world/4.read-video-vue/src/components/ImgRecognizer.vue
<template>
  <div class="ImgDecode"><input ref="iptRef" type="file" @change="decodeImg"/></div>
</template>

<script>
import { LabelRecognizer } from "keillion-dynamsoft-label-recognizer";
export default {
  name: 'ImgDecode',
  data() {
    return {
      pReader: null,
      reader: null
    }
  },
  async mounted() {
    this.reader = await (this.pReader = LabelRecognizer.createInstance({runtimeSettings: "letter"}));
  },
  methods: {
    async decodeImg(e) {
      try {
        let results = await this.reader.recognize(e.target.files[0]);
        for(let result of results){
          for(let line of result.lineResults) {
            alert(line.text);
            console.log(line.text);
          }
        }
        this.$refs.iptRef.value = '';
      } catch(ex) {
        console.error(ex);
      }
    }
  },
  async beforeDestroy() {
    if(this.pReader) {
      (await this.pReader).destroyContext();
      console.log('ImgRecognizer Component Unmount');
    }
  },
}
</script>

<style scoped>
  .ImgDecode {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 90%;
    border: 1px solid black
  }
</style>

// 1.hello-world/3.read-video-react/src/components/ImgRecognizer/ImgRecognizer.js
import React, { Component } from 'react'
import { LabelRecognizer } from "keillion-dynamsoft-label-recognizer";
import './ImgRecognizer.css'

export default class ImgDecode extends Component {
  constructor(props) {
    super(props);
    this.pReader = null;
    this.reader = null;
    this.iptRef = React.createRef();
  }

  async componentDidMount() {
    this.reader = await (this.pReader = LabelRecognizer.createInstance({runtimeSettings: "letter"}));
  }

  decodeImg = async (e) => {
    try {
      let results = await this.reader.recognize(e.target.files[0]);
      for(let result of results){
        for(let line of result.lineResults) {
          alert(line.text);
          console.log(line.text);
        }
      }
      this.iptRef.current.value = '';
    } catch(ex) {
      console.error(ex);
    }
  }

  async componentWillUnmount() {
    if (this.pReader) {
      (await this.pReader).destroyContext();
      console.log('ImgDecode Component Unmount');
    }
  }

  render() {
    return (
      <div className="ImgDecode"><input type="file" ref={this.iptRef} onChange={this.decodeImg}/></div>
    )
  }
}
