// 1.hello-world/3.read-video-react/src/components/LabelRecognizer.js
import DLR from "../dlr";
import DCE from "../dce";
import React from 'react';
import './LabelRecognizer.css';

class LabelRecognizer extends React.Component {
    constructor(props) {
        super(props);
        this.bDestroyed = false;
        this.pRecognizer = null;
        this.pCameraEnhancer = null;
        this.elRef = React.createRef();
    }
    async componentDidMount() {
        try {
            let cameraEnhancer = await (this.pCameraEnhancer = this.pCameraEnhancer || DCE.createInstance());
            let recognizer = await (this.pRecognizer = this.pRecognizer || DLR.createInstance({
                runtimeSettings: "video-letter"
            }))
            await cameraEnhancer.setUIElement(DLR.defaultUIElementURL);
            recognizer.cameraEnhancer = cameraEnhancer;

            await recognizer.startScanning(true);

            if (this.bDestroyed) {
                recognizer.destroy();
                return;
            }

            recognizer.onFrameRead = results => {
                for (let result of results) {
                    for (let lineResult of result.lineResults) {
                        console.log(lineResult.text);
                        this.props.appendMessage({ format: lineResult.format, text: lineResult.text, type: "result" });
                        if (lineResult.text.indexOf("Attention(exceptionCode") !== -1) {
                            this.props.appendMessage({ msg: lineResult.exception.message, type: "error" });
                        }
                    }
                }
            };

            recognizer.onUniqueRead = (txt) => {
                alert(txt);
                console.log("Unique Code Found: " + txt);
            }
        } catch (ex) {
            this.props.appendMessage({ msg: ex.message, type: "error" });
            console.error(ex);
        }
    }
    async componentWillUnmount() {
        this.bDestroyed = true;
        if (this.pRecognizer) {
            (await this.pRecognizer).destroy();
        }
    }
    shouldComponentUpdate() {
        return false;
    }
    render() {
        return (
            <div ref={this.elRef} style={{ width: "100%", height: "100%" }}></div>
        );
    }
}

export default LabelRecognizer;

// 1.hello-world/6.read-video-nuxtjs/components/LabelRecognizer.vue
<template>
  <div id="labelRecognizerUI"></div>
</template>

<script>
import DLR from "../dlr";
import DCE from "../dce";

export default {
  data() {
    return {
      bDestroyed: false,
      pRecognizer: null,
      pCameraEnhancer: null
    };
  },
    async mounted() {
        try {

            let cameraEnhancer = await (this.pCameraEnhancer = this.pCameraEnhancer || DCE.createInstance());
            let recognizer = await (this.pRecognizer = this.pRecognizer || DLR.createInstance({
                runtimeSettings: "video-letter"
            }));

            await cameraEnhancer.setUIElement(DLR.defaultUIElementURL);
            recognizer.cameraEnhancer = cameraEnhancer;

            await recognizer.startScanning(true);

            if (this.bDestroyed) {
                recognizer.destroy();
                cameraEnhancer.destroy();
                return;
            }

            recognizer.onFrameRead = (results) => {
                for (let result of results) {
                    for (let lineResult of result.lineResults) {
                        console.log(lineResult.text);
                    }
                }
            };
            recognizer.onUniqueRead = (txt) => {
                alert(txt);
                console.log("Unique Code Found: " + txt);
            }
        } catch (ex) {
            this.$emit("appendMessage", { msg: ex.message, type: "error" });
            console.error(ex);
        }
    },
    async beforeDestroy() {
        if (this.pRecognizer) {
            (await this.pRecognizer).destroy();
            (await this.pCameraEnhancer).destroy();
            this.bDestroyed = true;
        }
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#barcodeScannerUI {
  width: 100%;
  height: 100%;
}
</style>
