// hello-world/read-video-vue/src/components/ImageRecognizer.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, type Ref } from "vue";
import type { TextLineResultItem } from "@dynamsoft/dynamsoft-label-recognizer"
import { CaptureVisionRouter } from "dynamsoft-capture-vision-router";

const iptRef: Ref<HTMLInputElement | null> = ref(null);
const resRef: Ref<HTMLDivElement | null> = ref(null);
const pRouter: Ref<Promise<CaptureVisionRouter> | null> = ref(null);

onMounted(()=>{
    pRouter.value = CaptureVisionRouter.createInstance();
})

onUnmounted(async()=>{
    (await pRouter.value)!.dispose();
    console.log('ImageRecognizer Component Unmount');
})

const captureImage = async (e: any) => {
    try {
        resRef.value!.innerText = "";
        const router = await pRouter.value;
        const results = await router!.capture(e.target.files[0]);
        const res = [];
        for(let result of results.items){
            console.log((result as TextLineResultItem).text);
            res.push((result as TextLineResultItem).text);
        }
        resRef.value!.innerText = res.join("\n");
        iptRef.value!.value = '';
    } catch(ex:any) {
        let errMsg: string;
        if (ex.message.includes("network connection error")) {
            errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
        } else {
            errMsg = ex.message||ex;
        }
        console.error(errMsg);
        alert(errMsg);
    }
}
</script>

<template>
    <div class="capture-img">
        <div class="img-ipt"><input type="file" ref="iptRef" @change="captureImage"/></div>
        <div class="result-area" ref="resRef"></div>
    </div>
</template>
    
<style scoped>
.capture-img {
  width: 100%;
  height: 100%;
  font-family:Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New, monospace;
}

.capture-img .img-ipt {
  width: 80%;
  height: 100%;
  display: flex;
  justify-content: center;
  border: 1px solid black;
  margin: 0 auto;
}

.capture-img .result-area {
  margin-top: 20px;
}
</style>

// hello-world/read-video-react/src/components/ImageRecognizer/ImageRecognizer.tsx
import { useEffect, useRef, MutableRefObject } from "react";
import type { TextLineResultItem } from "@dynamsoft/dynamsoft-label-recognizer"
import { CaptureVisionRouter } from "dynamsoft-capture-vision-router";
import "./ImageRecognizer.css";

function ImageRecognizer() {
    const iptRef: MutableRefObject<HTMLInputElement | null> = useRef(null);
    const resRef: MutableRefObject<HTMLDivElement | null> = useRef(null);
    const pRouter: MutableRefObject<Promise<CaptureVisionRouter> | null> = useRef(null);

    useEffect((): any => {
        pRouter.current = CaptureVisionRouter.createInstance();

        return async () => {
            (await pRouter.current)!.dispose();
            console.log('ImageRecognizer Component Unmount');
        }
    }, []);

    const captureImage = async (e: any) => {
        try {
            resRef.current!.innerText = "";
            const router = await pRouter.current;
            const results = await router!.capture(e.target.files[0]);
            const res = [];
            for (let result of results.items) {
                console.log((result as TextLineResultItem).text);
                res.push((result as TextLineResultItem).text);
            }
            resRef.current!.innerText = res.join("\n");
            iptRef.current!.value = '';
        } catch (ex: any) {
            let errMsg: string;
            if (ex.message.includes("network connection error")) {
                errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
            } else {
                errMsg = ex.message || ex;
            }
            console.error(errMsg);
            alert(errMsg);
        }
    }

    return (
        <div className="capture-img">
            <div className="img-ipt"><input type="file" ref={iptRef} onChange={captureImage} /></div>
            <div className="result-area" ref={resRef}></div>
        </div>
    )
}

export default ImageRecognizer;
