// 1.hello-world/3.read-video-angular/src/app/hello-world/hello-world.component.ts
import { Component, OnInit } from '@angular/core';
import '../dce'; // import side effects. The license, engineResourcePath, so on.
import '../dlr'; // import side effects. The license, engineResourcePath, so on.
import { LabelRecognizer } from "dynamsoft-label-recognizer";

@Component({
  selector: 'app-hello-world',
  templateUrl: './hello-world.component.html',
  styleUrls: ['./hello-world.component.css']
})
export class HelloWorldComponent implements OnInit {
  bShowRecognizer = true;
  bShowImgDecode = false;
  async ngOnInit(): Promise<void> {
    // Load the library on page load to speed things up.
    try {
      await LabelRecognizer.loadWasm();
    } catch (ex) {
      let errMsg: string;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
  }
  showScanner(): void {
    this.bShowRecognizer = true;
    this.bShowImgDecode = false;
  }
  showImgDecode(): void {
    this.bShowRecognizer = false;
    this.bShowImgDecode = true;
  }
}

<div class="helloWorld">
    <h1>Hello World for Angular<img style="height: 25px;" alt="logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
        />
    </h1>
    <div class="btn-group">
        <button [ngStyle]="{'margin-right': '10px', 'background-color': bShowRecognizer ? 'rgb(255,174,55)' : 'white'}" (click)="showScanner()">Video Recognizer</button>
        <button [ngStyle]="{'background-color': !bShowRecognizer ? 'rgb(255,174,55)' : 'white'}" (click)="showImgDecode()">Image Recognizer</button>
    </div>
    <div class="container">
        <app-video-recognizer *ngIf="bShowRecognizer"></app-video-recognizer>
        <app-image-recognizer *ngIf="bShowImgDecode"></app-image-recognizer>
    </div>
</div>

// 1.hello-world/4.read-video-react/src/components/HelloWorld/HelloWorld.js
import './HelloWorld.css';
import reactLogo from '../../logo.svg';
import { LabelRecognizer } from "dynamsoft-label-recognizer";
import React from 'react';
import VideoRecognizer from '../VideoRecognizer/VideoRecognizer';
import ImgRecognizer from '../ImgRecognizer/ImgRecognizer';

class HelloWorld extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            libLoaded: false,
            bShowRecognizer: true,
            bShowImgDecode: false, 
        };
    }
    async componentDidMount() {
        try {
            await LabelRecognizer.loadWasm();
            this.setState(state => {
                state.libLoaded = true;
                return state;
            }, () => {
                this.showRecognizer();
            });
        } catch (ex) {
            let errMsg;
            if (ex.message.includes("network connection error")) {
                errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
            } else {
                errMsg = ex.message||ex;
            }
            console.error(errMsg);
            alert(errMsg);
        }
    }

    showRecognizer = () => {
        this.setState({
            bShowRecognizer: true,
            bShowImgDecode: false
        });
    }

    showImgDecode = () => {
        this.setState({
            bShowRecognizer: false,
            bShowImgDecode: true
        });
    }

    render() {
        return (
            <div className="helloWorld">
                <h1>Hello World for React<img src={reactLogo} className="App-logo" alt="logo" /></h1>
                {
                    this.state.libLoaded ? 
                    <div className="btn-group">
                        <button style={{marginRight: '10px', backgroundColor: this.state.bShowRecognizer ? 'rgb(255,174,55)' : 'white'}} onClick={this.showRecognizer}>Video Recognizer</button>
                        <button style={{backgroundColor: this.state.bShowImgDecode ? 'rgb(255,174,55)' : 'white'}} onClick={this.showImgDecode}>Image Recognizer</button>
                    </div> :
                    ''
                }
                <div id="UIElement">
                    {!this.state.libLoaded ? (<span style={{ fontSize: "x-large" }}>Loading Library...</span>) : ""}
                    {this.state.bShowRecognizer ? (<VideoRecognizer></VideoRecognizer>) : ""}
                    {this.state.bShowImgDecode ? (<ImgRecognizer></ImgRecognizer>) : ""}
                </div>
            </div>
        );
    }
}
export default HelloWorld;
