// hello-world/read-video-nextjs/components/ImageRecognizer/ImageRecognizer.tsx
"use client"

import { useEffect, useRef, MutableRefObject } from "react";
import type { TextLineResultItem } from "@dynamsoft/dynamsoft-label-recognizer"
import { CaptureVisionRouter } from "dynamsoft-capture-vision-router";
import "./ImageRecognizer.css";

function ImageRecognizer() {
    const iptRef: MutableRefObject<HTMLInputElement | null> = useRef(null);
    const resRef: MutableRefObject<HTMLDivElement | null> = useRef(null);
    const pRouter: MutableRefObject<Promise<CaptureVisionRouter> | null> = useRef(null);

    useEffect((): any => {
        pRouter.current = CaptureVisionRouter.createInstance();

        return async () => {
            (await pRouter.current)!.dispose();
            console.log('ImageRecognizer Component Unmount');
        }
    }, []);

    const captureImage = async (e: any) => {
        try {
            resRef.current!.innerText = "";
            const router = await pRouter.current;
            const results = await router!.capture(e.target.files[0]);
            const res = [];
            for (let result of results.items) {
                console.log((result as TextLineResultItem).text);
                res.push((result as TextLineResultItem).text);
            }
            resRef.current!.innerText = res.join("\n");
            iptRef.current!.value = '';
        } catch (ex: any) {
            let errMsg: string;
            if (ex.message.includes("network connection error")) {
                errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
            } else {
                errMsg = ex.message || ex;
            }
            console.error(errMsg);
            alert(errMsg);
        }
    }

    return (
        <div className="capture-img">
            <div className="img-ipt"><input type="file" ref={iptRef} onChange={captureImage} /></div>
            <div className="result-area" ref={resRef}></div>
        </div>
    )
}

export default ImageRecognizer;

// hello-world/read-video-angular/src/app/image-recognizer/image-recognizer.component.ts
import { Component, ViewChild } from '@angular/core';
import type { TextLineResultItem } from "@dynamsoft/dynamsoft-label-recognizer"
import { CaptureVisionRouter } from "dynamsoft-capture-vision-router";

@Component({
  selector: 'app-image-recognizer',
  templateUrl: './image-recognizer.component.html',
  styleUrls: ['./image-recognizer.component.css']
})
export class ImageRecognizerComponent {
  pRouter: Promise<CaptureVisionRouter> | null = null;

  @ViewChild('iptRef') iptRef: any;
  @ViewChild('resRef') resRef: any;

  ngOnInit(): void {
    this.pRouter = CaptureVisionRouter.createInstance();
  }

  captureImage = async (e: any) => {
    try {
      this.resRef!.innerText = "";
      const router = await this.pRouter;
      const results = await router!.capture(e.target.files[0]);
      const res = [];
      for (let result of results.items) {
        console.log((result as TextLineResultItem).text);
        res.push((result as TextLineResultItem).text);
      }
      this.resRef.nativeElement!.innerText = res.join("\n");
      this.iptRef.nativeElement!.value = '';
    } catch (ex: any) {
      let errMsg: string;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message || ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
  }

  async ngOnDestroy() {
    (await this.pRouter)!.dispose();
    console.log('ImageRecognizer Component Unmount');
  }
}

<div class="recognize-img">
  <div class="img-ipt"><input type="file" #iptRef (change)="recognizeImg($event)"/></div>
  <div class="result-area" #resRef></div>
</div>
