// 1.hello-world/read-video-react/src/components/ImgRecognizer/ImgRecognizer.js
import React, { Component } from 'react'
import { LabelRecognizer } from "dynamsoft-label-recognizer";
import './ImgRecognizer.css'

export default class ImgRecognizer extends Component {
  constructor(props) {
    super(props);
    this.pRecognizer = null;
    this.iptRef = React.createRef();
  }

  async componentDidMount() {
    await (this.pRecognizer = LabelRecognizer.createInstance({runtimeSettings: "numberletter"}));
  }

  recognizeImg = async (e) => {
    try {
      const recognizer = await this.pRecognizer;
      let results = await recognizer.recognize(e.target.files[0]);
      for(let result of results){
        for(let line of result.lineResults) {
          alert(line.text);
          console.log(line.text);
        }
      }
      this.iptRef.current.value = '';
    } catch(ex) {
      let errMsg;
      if (ex.message.includes("network connection error")) {
        errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
        errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
  }

  async componentWillUnmount() {
    if (this.pRecognizer) {
      (await this.pRecognizer).destroyContext();
      console.log('ImgRecognize Component Unmount');
    }
  }

  render() {
    return (
      <div className="recognizeImg"><input type="file" ref={this.iptRef} onChange={this.recognizeImg}/></div>
    )
  }
}

// 1.hello-world/read-video-vue3/src/components/ImgRecognizer.vue
<template>
  <div class="ImgRecognize"><input type="file" ref="iptRef" @change="recognizeImg"/></div>
</template>

<script>
import { onBeforeUnmount, onMounted, ref } from '@vue/runtime-core';
import { LabelRecognizer } from "dynamsoft-label-recognizer";
export default {
  name: 'ImgRecognizer',
  setup() {
    const iptRef = ref(null);
    const pRecognizer = ref(null);

    onMounted(async ()=>{
      await (pRecognizer.value = LabelRecognizer.createInstance({runtimeSettings: "numberletter"}));
    })

    const recognizeImg = async (e) => {
      try {
        const recognizer = await pRecognizer.value;
        let results = await recognizer.recognize(e.target.files[0]);
        for(let result of results){
          for(let line of result.lineResults) {
            alert(line.text);
            console.log(line.text);
          }
        }
        iptRef.value.value = '';
      } catch(ex) {
        let errMsg;
        if (ex.message.includes("network connection error")) {
            errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
        } else {
            errMsg = ex.message||ex;
        }
        console.error(errMsg);
        alert(errMsg);
      }
    }

    onBeforeUnmount(async ()=>{
      if(pRecognizer.value) {
        (await pRecognizer.value).destroyContext();
        console.log('ImgRecognizer Component Unmount');
      }
    })

    return {
      recognizeImg,
      iptRef
    }
  },
}
</script>

<style scoped>
  .ImgRecognize {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 90%;
    border: 1px solid black
  }
</style>
