// hello-world/read-video-react/src/components/HelloWorld/HelloWorld.js
import './HelloWorld.css';
import reactLogo from '../../logo.svg';
import { LabelRecognizer } from "dynamsoft-label-recognizer";
import React from 'react';
import VideoRecognizer from '../VideoRecognizer/VideoRecognizer';
import ImgRecognizer from '../ImgRecognizer/ImgRecognizer';

class HelloWorld extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            libLoaded: false,
            bShowRecognizer: true,
            bShowImgRecognize: false, 
        };
    }
    async componentDidMount() {
        try {
            await LabelRecognizer.loadWasm();
            this.setState(state => {
                state.libLoaded = true;
                return state;
            }, () => {
                this.showRecognizer();
            });
        } catch (ex) {
            let errMsg;
            if (ex.message.includes("network connection error")) {
                errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
            } else {
                errMsg = ex.message||ex;
            }
            console.error(errMsg);
            alert(errMsg);
        }
    }

    showRecognizer = () => {
        this.setState({
            bShowRecognizer: true,
            bShowImgRecognize: false
        });
    }

    showImgRecognize = () => {
        this.setState({
            bShowRecognizer: false,
            bShowImgRecognize: true
        });
    }

    render() {
        return (
            <div className="helloWorld">
                <h1>Hello World for React<img src={reactLogo} className="App-logo" alt="logo" /></h1>
                {
                    this.state.libLoaded ? 
                    <div className="btn-group">
                        <button style={{marginRight: '10px', backgroundColor: this.state.bShowRecognizer ? 'rgb(255,174,55)' : 'white'}} onClick={this.showRecognizer}>Video Recognizer</button>
                        <button style={{backgroundColor: this.state.bShowImgRecognize ? 'rgb(255,174,55)' : 'white'}} onClick={this.showImgRecognize}>Image Recognizer</button>
                    </div> :
                    ''
                }
                <div id="UIElement">
                    {!this.state.libLoaded ? (<span style={{ fontSize: "x-large" }}>Loading Library...</span>) : ""}
                    {this.state.bShowRecognizer ? (<VideoRecognizer></VideoRecognizer>) : ""}
                    {this.state.bShowImgRecognize ? (<ImgRecognizer></ImgRecognizer>) : ""}
                </div>
            </div>
        );
    }
}
export default HelloWorld;

// hello-world/read-video-nuxtjs/components/HelloWorld.vue
<template>
  <div class="helloWorld">
    <h1>Hello World for Nuxtjs</h1>
    <div id="UIElement">
      <div class="btn-group" v-if="libLoaded">
        <button :style="{marginRight: '10px', backgroundColor: bShowRecognizer ? 'rgb(255,174,55)' : 'white'}" @click="showRecognizer">Video Recognizer</button>
        <button :style="{backgroundColor: bShowImgRecognize ? 'rgb(255,174,55)' : 'white'}" @click="showImgRecognize">Image Recognizer</button>
      </div>
      <span style="font-size: x-large" v-if="!libLoaded">Loading Library...</span>
      <VideoRecognizer v-if="bShowRecognizer"></VideoRecognizer>
      <ImgRecognizer v-if="bShowImgRecognize"></ImgRecognizer>
    </div>
  </div>
</template>

<script>
import { LabelRecognizer } from "dynamsoft-label-recognizer";
import VideoRecognizer from "./VideoRecognizer";
import ImgRecognizer from './ImgRecognizer.vue'

export default {
  name: "HelloWorld",
  components: {
    VideoRecognizer, ImgRecognizer
  },
  data() {
    return {
      libLoaded: false,
      bShowRecognizer: true,
      bShowImgRecognize: false
    };
  },
  async mounted() {
    try {
      //Load the library on page load to speed things up.
      await LabelRecognizer.loadWasm();
      this.libLoaded = true;
      this.showRecognizer();
    } catch (ex) {
      let errMsg;
      if (ex.message.includes("network connection error")) {
          errMsg = "Failed to connect to Dynamsoft License Server: network connection error. Check your Internet connection or contact Dynamsoft Support (support@dynamsoft.com) to acquire an offline license.";
      } else {
          errMsg = ex.message||ex;
      }
      console.error(errMsg);
      alert(errMsg);
    }
  },
  methods: {
    showRecognizer() {
      this.bShowRecognizer = true;
      this.bShowImgRecognize = false;
    },
    showImgRecognize() {
      this.bShowRecognizer = false;
      this.bShowImgRecognize = true;
    }
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.helloWorld {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  color: #455a64;
}
h1 {
  font-size: 1.5em;
}
#UIElement {
  margin: 2vmin auto;
  text-align: center;
  font-size: medium;
  height: 40vh;
  width: 80vw;
}
button {
  font-size: 1.5rem;
  margin: 1.5vh 0;
  border: 1px solid black;
  background-color: white;
  color: black;
}
</style>
